apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp
spec:
  selector:
    matchLabels:
      app: tp
  template:
    metadata:
      labels:
        app: tp
    spec:
      containers:
      - name: tp
        image: chanou41/tp-kub:final
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tp-service
spec:
  selector:
    app: tp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
